service: sigeco-promocao-serverless

# Para teste local
plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-pseudo-parameters
custom:
  localstack:
    stages:
      - local
    autostart: false
  serverless-offline:
    useChildProcesses: true
  tags:
    dev: sigeco-promocao-api-dev
    prod: sigeco-promocao-api-prod
  endPonitSigecoApi:
    dev: https://feature-gcobo-432-promocao.devops.grancursosonline.com.br
    prod: https://sigeco-api.grancursosonline.com.br
  memory:
    dev: 2048
    prod: 2048
  secrets: ${ssm:/aws/reference/secretsmanager/USUARIO_SIGEGO-${self:provider.stage}~true}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    APP_ENV: ${self:provider.stage}
    URL_API_SIGECO: ${self:custom.endPonitSigecoApi.${self:provider.stage}}
    USER_SIGECO: ${self:custom.secrets.USER_SIGECO}
    PWD_USER_SIGECO: ${self:custom.secrets.PWD_USER_SIGECO}
      
functions:
  SchedulePromotion:
    role: arn:aws:iam::#{AWS::AccountId}:role/SchedulePromotionRole
    handler: src/handlers/scheduler/schedule_promotion_handler.main
    events:
      - http:
          path: agendar-promocao
          method: post
    memorySize: ${self:custom.memory.${self:provider.stage}}
  DeleteSchedulePromotion:
    role: arn:aws:iam::#{AWS::AccountId}:role/DeleteSchedulePromotionRole
    handler: src/handlers/scheduler/delete_schedule_promotion_handler.main
    events:
      - http:
          path: agendar-promocao
          method: delete
    memorySize: ${self:custom.memory.${self:provider.stage}}
  PromotionActivator:
    role: arn:aws:iam::#{AWS::AccountId}:role/PromotionActivatorRole
    handler: src/handlers/activator/promotion_activator_handler.main
    memorySize: ${self:custom.memory.${self:provider.stage}}

resources:
  Resources:
    PermissionToCallPromotionActivator:
      Type: "AWS::Lambda::Permission"
      Properties: 
        Action: lambda:InvokeFunction
        FunctionName: 
          Ref: PromotionActivatorLambdaFunction
        Principal: "events.amazonaws.com"
  Outputs:
    PromotionActivatorArn:
      Value:
        Fn::GetAtt: 
          - PromotionActivatorLambdaFunction
          - Arn
      Export:
        Name: PromotionActivatorArn-${self:provider.stage}