######################################                                                                                  
###                                ###
###        FUNCTIONS BLOCK         ###
###                                ### 
######################################
    
functions:

  SchedulePromotion:
    name: ${self:service}-schedule-promotion-${opt:stage}
    handler: src/handlers/scheduler/schedule_promotion_handler.main
    events:
      - http:
          path: agendar-promocao
          method: post
    memorySize: ${env:APP_MEMORY_SIZE}

  DeleteSchedulePromotion:
    name: ${self:service}-delete-schedule-promotion-${opt:stage}
    handler: src/handlers/scheduler/delete_schedule_promotion_handler.main
    events:
      - http:
          path: agendar-promocao
          method: delete
    memorySize: ${env:APP_MEMORY_SIZE}
    
  PromotionActivator:
    name: ${self:service}-promotion-activator-${opt:stage}
    handler: src/handlers/activator/promotion_activator_handler.main
    memorySize: ${env:APP_MEMORY_SIZE}

######################################                                                                                  
###                                ###
###       FRAMEWORK SETTINGS       ###
###                                ### 
######################################

useDotenv: true
service: ${env:APP_SERVICE_NAME}
variablesResolutionMode: "20210326"
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_LAMBDA_REGION, "sa-east-1"}
  lambdaHashingVersion: "20201221"
  iam:
    role: ${env:AWS_LAMBDA_ROLE, "dev"}
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupsIds.${opt:stage}}
    subnetIds:
      - ${self:custom.subnetIds.${opt:stage}.sub1}
      - ${self:custom.subnetIds.${opt:stage}.sub2}
      - ${self:custom.subnetIds.${opt:stage}.sub3}

plugins:
  - serverless-dotenv-plugin
  - serverless-localstack
  - serverless-offline

package: 
  patterns: 
    - '!.git/**'
    - '!venv/**'
    - '!node_modules/**'
    - '!.vscode/**'
    - '!bitbucket-pipelines.yml'
    - '!package-lock.json'
    - '!package.json'
    - '!README.md'
    - '!requirements.txt'
  excludeDevDependencies: false 

custom:
  localstack:
    stages:
      - local
    autostart: false

  serverless-offline:
    useChildProcesses: true
  
  securityGroupsIds:
    dev: ${env:AWS_LAMBDA_SG_DEV_ID, "dev"}
    prd: ${env:AWS_LAMBDA_SG_PRD_ID, "dev"}

  subnetIds:
    dev:
      sub1: ${env:AWS_LAMBDA_SUBNET_DEV_1, "dev"}
      sub2: ${env:AWS_LAMBDA_SUBNET_DEV_2, "dev"}
      sub3: ${env:AWS_LAMBDA_SUBNET_DEV_3, "dev"}
    prd:
      sub1: ${env:AWS_LAMBDA_SUBNET_PRD_1, "prd"}
      sub2: ${env:AWS_LAMBDA_SUBNET_PRD_2, "prd"}
      sub3: ${env:AWS_LAMBDA_SUBNET_PRD_3, "prd"}